# Generated by Django 5.0.6 on 2024-05-27 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branchCode', models.AutoField(primary_key=True, serialize=False)),
                ('branchName', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('totalAssets', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idNumber', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('accountId', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('openDate', models.DateField()),
                ('creditBalance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('usedCredit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lastRepaymentDate', models.DateField()),
                ('lastUseDate', models.DateField()),
                ('interestRate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('accountId', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('openDate', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interestRate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentId', models.AutoField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=100)),
                ('departmentType', models.CharField(max_length=100)),
                ('branchId', models.ForeignKey(db_column='branchCode', on_delete=django.db.models.deletion.CASCADE, to='bank_management.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeId', models.AutoField(primary_key=True, serialize=False)),
                ('idCard', models.CharField(max_length=18)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('phoneNumber', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=200)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hireDate', models.DateField()),
                ('position', models.CharField(max_length=100)),
                ('branchId', models.ForeignKey(db_column='branchCode', on_delete=django.db.models.deletion.CASCADE, to='bank_management.branch')),
                ('departmentId', models.ForeignKey(db_column='departmentId', on_delete=django.db.models.deletion.CASCADE, to='bank_management.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(db_column='employeeId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_management.employee'),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loanId', models.AutoField(primary_key=True, serialize=False)),
                ('repaymentAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interestRate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loanDate', models.DateTimeField()),
                ('loanStatus', models.CharField(choices=[('NOT_ISSUED', '未发放'), ('ISSUED', '已发放'), ('PAID_OFF', '已还清')], default='NOT_ISSUED', max_length=10)),
                ('branchIssued', models.ForeignKey(db_column='branchCode', on_delete=django.db.models.deletion.CASCADE, to='bank_management.branch')),
                ('clientId', models.ForeignKey(db_column='idCard', on_delete=django.db.models.deletion.CASCADE, to='bank_management.client')),
            ],
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('repaymentId', models.AutoField(primary_key=True, serialize=False)),
                ('repaymentAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('repaymentDate', models.DateField()),
                ('loanId', models.ForeignKey(db_column='loanId', on_delete=django.db.models.deletion.CASCADE, to='bank_management.loan')),
            ],
        ),
    ]
