# Generated by Django 5.0.6 on 2024-05-28 01:43

from django.db import migrations

def create_branch(apps, schema_editor):
    Branch = apps.get_model('bank_management', 'Branch')
    Branch.objects.create(branchName='合肥主分行', location='合肥市蜀山区', totalAssets=5000000.00)
    Branch.objects.create(branchName='合肥北城分行', location='合肥市包河区', totalAssets=6000000.00)
    Branch.objects.create(branchName='合肥南城分行', location='合肥市庐阳区', totalAssets=7000000.00)
    Branch.objects.create(branchName='合肥西城分行', location='合肥市瑶海区', totalAssets=8000000.00)

class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0002_auto_20240527_1344'),
    ]

    operations = [
        migrations.RunPython(create_branch),
    ]
