# Generated by Django 5.0.6 on 2024-05-28 02:01

from django.db import migrations

def create_departments(apps, schema_editor):
    Department = apps.get_model('bank_management', 'Department')
    Branch = apps.get_model('bank_management', 'Branch')

    for branch_id in range(1, 5):
        branch = Branch.objects.get(branchCode=branch_id)
        Department.objects.create(departmentName=f'Department A of Branch {branch_id}', branchId=branch)
        Department.objects.create(departmentName=f'Department B of Branch {branch_id}', branchId=branch)
        Department.objects.create(departmentName=f'Department C of Branch {branch_id}', branchId=branch)
        Department.objects.create(departmentName=f'Department D of Branch {branch_id}', branchId=branch)

class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0003_auto_20240528_0143'),
    ]

    operations = [
        migrations.RunPython(create_departments),
    ]