# Generated by Django 5.0.6 on 2024-06-01 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0010_auto_20240601_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditaccount',
            name='idNumber',
            field=models.ForeignKey(db_column='idNumber', null=True, on_delete=django.db.models.deletion.CASCADE, to='bank_management.client'),
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='idNumber',
            field=models.ForeignKey(db_column='idNumber', null=True, on_delete=django.db.models.deletion.CASCADE, to='bank_management.client'),
        ),
    ]
