# Generated by Django 5.0.6 on 2024-06-01 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0012_auto_20240601_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditaccount',
            name='branchCode',
            field=models.ForeignKey(db_column='branchCode', null=True, on_delete=django.db.models.deletion.CASCADE, to='bank_management.branch'),
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='branchCode',
            field=models.ForeignKey(db_column='branchCode', null=True, on_delete=django.db.models.deletion.CASCADE, to='bank_management.branch'),
        ),
    ]
