# Generated by Django 5.0.6 on 2024-06-01 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0013_creditaccount_branchcode_savingsaccount_branchcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('transactionDate', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transactionType', models.CharField(choices=[('DEPOSIT', '存款'), ('WITHDRAWAL', '取款')], max_length=10)),
                ('savingsAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_management.savingsaccount')),
            ],
        ),
    ]
