# Generated by Django 5.0.6 on 2024-06-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0014_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionType',
            field=models.CharField(choices=[('DEPOSIT', '存款'), ('WITHDRAWAL', '取款'), ('TRANSFER', '转账')], max_length=10),
        ),
    ]
