# Generated by Django 5.0.6 on 2024-06-05 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0020_alter_transaction_savingsaccount'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            DROP TRIGGER IF EXISTS calculate_interest_after_insert_on_transaction;
            '''
        ),
        migrations.RunSQL(
            '''
            CREATE TRIGGER calculate_interest_after_insert_on_transaction
            AFTER INSERT ON bank_management_transaction
            FOR EACH ROW
            BEGIN
                DECLARE interest DECIMAL(12, 2);
                DECLARE days INT;
                DECLARE old_balance DECIMAL(12, 2);
                DECLARE new_balance DECIMAL(12, 2);
                DECLARE interest_rate DECIMAL(4, 2);

                SELECT balance, interestRate INTO old_balance, interest_rate FROM bank_management_savingsaccount WHERE accountId = NEW.accountId;

                IF NEW.transactionType = 'DEPOSIT' OR NEW.transactionType = 'INCOME' THEN
                    SET new_balance = old_balance + NEW.amount;
                ELSEIF NEW.transactionType = 'WITHDRAWAL' OR NEW.transactionType = 'TRANSFER' THEN
                    SET new_balance = old_balance - NEW.amount;
                END IF;

                UPDATE bank_management_savingsaccount SET balance = new_balance WHERE accountId = NEW.accountId;
            END;
            '''
        ),
    ]
