# Generated by Django 5.0.6 on 2024-06-05 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0022_create_savingsaccount_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsaccount',
            name='lastTransaction',
        ),
    ]
