# Generated by Django 5.0.6 on 2024-06-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0023_remove_savingsaccount_lasttransaction'),
    ]

    operations = [
         migrations.RunSQL(
            '''
            DROP TRIGGER IF EXISTS calculate_interest_after_insert_on_transaction;
            '''
        ),
    ]
