# Generated by Django 5.0.6 on 2024-06-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0025_create_transactioion_trigger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditaccount',
            old_name='usedCredit',
            new_name='creditLimit',
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
