# Generated by Django 5.0.6 on 2024-06-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0030_create_creditaccount_event11'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='transactionType',
            field=models.CharField(choices=[('CONSUME', '消费'), ('PAYMENT', '还款')], max_length=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loanDate',
            field=models.DateField(null=True),
        ),
    ]
