# Generated by Django 5.0.6 on 2024-06-06 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0031_alter_credittransaction_transactiontype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='principal',
            new_name='amount',
        ),
    ]
