# Generated by Django 5.0.6 on 2024-06-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0032_rename_principal_loan_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loanDays',
            field=models.IntegerField(null=True),
        ),
    ]
