# Generated by Django 5.0.6 on 2024-06-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0033_loan_loandays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interestRate',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loanStatus',
            field=models.CharField(choices=[('NOT_ISSUED', '未发放'), ('ISSUED', '已发放'), ('PAID_OFF', '已还清'), ('OVERDUE', '逾期')], default='NOT_ISSUED', max_length=10),
        ),
    ]
