# Generated by Django 5.0.6 on 2024-06-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0034_alter_loan_interestrate_alter_loan_loanstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='interest',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
