# Generated by Django 5.0.6 on 2024-06-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0036_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/'),
        ),
    ]
