# Generated by Django 5.0.6 on 2024-06-10 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0038_change_user_avatar'),
    ]

    operations = [
        migrations.RunSQL(
            """
            drop trigger if exists decrease_total_assets;
            drop trigger if exists increase_total_assets;
            """
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER decrease_total_assets
            AFTER UPDATE ON bank_management_loan
            FOR EACH ROW
            BEGIN
                IF NEW.loanStatus = 'ISSUED' AND OLD.loanStatus != 'ISSUED' THEN
                    UPDATE bank_management_branch
                    SET totalAssets = totalAssets - NEW.amount
                    WHERE branchCode = NEW.branchCode;
                END IF;
            END;
            """
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER increase_total_assets
            AFTER INSERT ON bank_management_repayment
            FOR EACH ROW
            BEGIN
                DECLARE branch_code INT;
                SELECT branchCode INTO branch_code FROM bank_management_loan WHERE loanId = NEW.loanId;
                UPDATE bank_management_branch
                SET totalAssets = totalAssets + NEW.repaymentAmount
                WHERE branchCode = branch_code;
            END;
            """
        )
    ]
