# Generated by Django 5.0.6 on 2024-06-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0041_change_update_insert_manager_trigger1'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP EVENT IF EXISTS check_loan_overdue;
            """
        ),
        migrations.RunSQL(
            """
            CREATE EVENT IF NOT EXISTS check_loan_overdue
            ON SCHEDULE EVERY 1 DAY
            STARTS CURRENT_DATE
            DO
            BEGIN
                UPDATE bank_management_loans
                SET loanStatus = 'OVERDUE'
                WHERE loanDate + INTERVAL loanDays DAY < CURRENT_DATE AND loanStatus = 'ISSUED';
                
                UPDATE bank_management_loans
                SET interest = interest + amount * interestRate * 5
                WHERE loanStatus = 'OVERDUE';
            END;
            """
        ),
    ]
