# Generated by Django 5.0.6 on 2024-05-28 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0004_auto_20240528_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='departmentType',
        ),
    ]
