# Generated by Django 5.0.6 on 2024-05-28 02:30

from django.db import migrations
import random
from django.utils import timezone
from decimal import Decimal

def create_employees(apps, schema_editor):
    Department = apps.get_model('bank_management', 'Department')
    Employee = apps.get_model('bank_management', 'Employee')

    addresses = ['123 Main St', '456 Maple Ave', '789 Oak Dr', '1011 Pine Rd']  # 地址列表

    for department in Department.objects.all():
        employees = []  # 存储每个部门的员工
        for i in range(1, 5):
            hire_date = timezone.now() - timezone.timedelta(days=random.randint(1, 365))  # 随机生成雇佣日期
            phone_number = '1' + ''.join(random.choice('34578') + ''.join(random.choice('0123456789') for _ in range(9)))  # 随机生成电话号码
            address = random.choice(addresses)  # 随机选择一个地址
            employee = Employee.objects.create(
                idCard=f'123456789{i}',
                name=f'Employee {i} of {department.departmentName}',
                gender='Male',
                phoneNumber=phone_number,
                address=address,
                salary=Decimal('5000.00'),
                hireDate=hire_date,
                position='Employee',
                departmentId=department,
                branchId=department.branchId,
            )
            employees.append(employee)

        # 选择一个员工作为经理，并增加他们的工资
        manager = random.choice(employees)
        manager.position = 'Manager'
        manager.salary += Decimal('3000.00')  # 增加经理的工资
        manager.save()
        department.manager = manager
        department.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0005_remove_department_departmenttype'),
    ]

    operations = [
        migrations.RunPython(create_employees),
    ]
