# Generated by Django 5.0.6 on 2024-05-31 03:28

from django.db import migrations

def update_employee_position(apps, schema_editor):
    Employee = apps.get_model('bank_management', 'Employee')
    Employee.objects.filter(employeeId__in=[2, 8, 12, 14, 20, 21, 27, 29]).update(position='Manager')

class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0006_auto_20240528_0230'),
    ]

    operations = [
        migrations.RunPython(update_employee_position),
    ]
