# Generated by Django 5.0.6 on 2024-05-31 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0007_auto_20240531_0328'),
    ]

    operations = [
        migrations.RunSQL("""
            DROP TRIGGER IF EXISTS update_manager_trigger;
            DROP TRIGGER IF EXISTS insert_manager_trigger;
        """),
        migrations.RunSQL("""
            CREATE TRIGGER update_manager_trigger
            AFTER UPDATE ON bank_management_department
            FOR EACH ROW 
            BEGIN
                IF NEW.employeeId <> OLD.employeeId THEN
                    UPDATE bank_management_employee
                    SET position = 'Manager', 
                        departmentId = NEW.departmentId,
                        branchCode = (SELECT branchCode FROM bank_management_department WHERE departmentId = NEW.departmentId)
                    WHERE employeeId = NEW.employeeId AND position <> 'Manager';

                    UPDATE bank_management_employee
                    SET position = 'Manager', 
                        salary = salary + 5000,
                        departmentId = NEW.departmentId,
                        branchCode = (SELECT branchCode FROM bank_management_department WHERE departmentId = NEW.departmentId)
                    WHERE employeeId = NEW.employeeId AND position = 'Manager';

                    UPDATE bank_management_employee
                    SET position = 'Employee',
                        salary = salary - 5000
                    WHERE employeeId = OLD.employeeId;
                END IF;
            END;
        """),
        migrations.RunSQL("""
            CREATE TRIGGER insert_manager_trigger
            AFTER INSERT ON bank_management_department
            FOR EACH ROW 
            BEGIN
                UPDATE bank_management_employee
                SET position = 'Manager', 
                    salary = salary + 5000,
                    departmentId = NEW.departmentId,
                    branchCode = (SELECT branchCode FROM bank_management_department WHERE departmentId = NEW.departmentId)
                WHERE employeeId = NEW.employeeId AND position <> 'Manager';

                UPDATE bank_management_employee
                SET position = 'Manager', 
                    departmentId = NEW.departmentId,
                    branchCode = (SELECT branchCode FROM bank_management_department WHERE departmentId = NEW.departmentId)
                WHERE employeeId = NEW.employeeId AND position = 'Manager';
            END;
        """),
    ]
