# Generated by Django 5.0.6 on 2024-06-01 06:56

from django.db import migrations
import random
from bank_management.models import Client
def idCardCheck():
    # 地址码
    addr_code = ''.join(random.choice('1234567890') for _ in range(6))
    # 随机生成一个在1995-2002之间的年份
    year = random.randint(1995, 2002)
    # 生成随机的月和日
    month = random.randint(1, 12)
    day = random.randint(1, 28)  # 为了简单起见，这里假设每个月都有28天
    # 出生日期码
    birth_code = '{:04d}{:02d}{:02d}'.format(year, month, day)
    # 顺序码
    order_code = ''.join(random.choice('1234567890') for _ in range(3))
    # 计算校验位
    check_code = calculate_check_code(addr_code + birth_code + order_code)
    # 返回身份证号码
    return addr_code + birth_code + order_code + check_code

def calculate_check_code(id17):
    # 加权因子
    weight_factor = [7, 9, 10, 5, 8, 4, 2, 1, 6, 3, 7, 9, 10, 5, 8, 4, 2]
    # 校验码映射
    check_code_dict = {0: '1', 1: '0', 2: 'X', 3: '9', 4: '8', 5: '7', 6: '6', 7: '5', 8: '4', 9: '3', 10: '2'}
    # 计算校验位
    sum = 0
    for i in range(0, len(id17)):
        sum += int(id17[i]) * weight_factor[i]
    return check_code_dict[sum % 11]

def create_clients(apps, schema_editor):
    names = ['张三', '李四', '王五', '赵六', '孙七']
    phone_prefixes = ['130', '131', '132', '133', '134', '135', '136', '137', '138', '139', '150', '151', '152', '153', '155', '156', '157', '158', '159', '180', '181', '182', '183', '185', '186', '187', '188', '189']
    addresses = ['北京市朝阳区', '上海市浦东新区', '广州市天河区', '深圳市南山区', '杭州市西湖区']

    for _ in range(10):  # 创建10个客户
        Client.objects.create(
            idNumber=idCardCheck(),
            name=random.choice(names),  # 从名字列表中随机选择一个
            phoneNumber=random.choice(phone_prefixes) + ''.join(random.choice('1234567890') for _ in range(8)),  # 生成电话号码
            address=random.choice(addresses) + str(random.randint(1, 100)) + '号'  # 生成地址
        )

class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0009_change_id_card'),
    ]

    operations = [
        migrations.RunPython(create_clients),
    ]
