# Generated by Django 5.0.6 on 2024-06-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0011_creditaccount_idnumber_savingsaccount_idnumber'),
    ]

    operations = [
    ]
