# Generated by Django 5.0.6 on 2024-06-05 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0015_alter_transaction_transactiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsaccount',
            name='lastTransactionDate',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('transactionDate', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transactionType', models.CharField(choices=[('TRANSFER', '转账'), ('PAYMENT', '还款')], max_length=10)),
                ('creditAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_management.creditaccount')),
            ],
        ),
    ]
