# Generated by Django 5.0.6 on 2024-06-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0016_savingsaccount_lasttransactiondate_credittransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditaccount',
            name='interestRate',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='interestRate',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
