# Generated by Django 5.0.6 on 2024-06-05 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0017_alter_creditaccount_interestrate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsaccount',
            name='lastTransactionDate',
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='lastTransaction',
            field=models.ForeignKey(db_column='transactionId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_management.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionType',
            field=models.CharField(choices=[('DEPOSIT', '存款'), ('WITHDRAWAL', '取款'), ('TRANSFER', '转账'), ('INCOME', '收入')], max_length=10),
        ),
    ]
