# Generated by Django 5.0.6 on 2024-06-05 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0021_alter_transaction_trigger'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            CREATE EVENT IF NOT EXISTS calculate_interest
            ON SCHEDULE EVERY 1 DAY
            STARTS CURRENT_TIMESTAMP
            DO
            BEGIN
                UPDATE bank_management_savingsaccount SET balance = balance + balance * interestRate where balance > 0;
            END;
            '''
        ),
    ]
