# Generated by Django 5.0.6 on 2024-06-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0024_drop_trigger'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            CREATE TRIGGER calculate_balance_after_insert_on_transaction
            AFTER INSERT ON bank_management_transaction
            FOR EACH ROW
            BEGIN
                DECLARE old_balance DECIMAL(12, 2);
                DECLARE new_balance DECIMAL(12, 2);

                SELECT balance INTO old_balance FROM bank_management_savingsaccount WHERE accountId = NEW.accountId;

                IF NEW.transactionType = 'DEPOSIT' OR NEW.transactionType = 'INCOME' THEN
                    SET new_balance = old_balance + NEW.amount;
                ELSEIF NEW.transactionType = 'WITHDRAWAL' OR NEW.transactionType = 'TRANSFER' THEN
                    SET new_balance = old_balance - NEW.amount;
                END IF;

                UPDATE bank_management_savingsaccount SET balance = new_balance WHERE accountId = NEW.accountId;
            END;
            '''
        ),
    ]
