# Generated by Django 5.0.6 on 2024-06-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0026_rename_usedcredit_creditaccount_creditlimit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditaccount',
            name='lastUseDate',
        ),
    ]
