# Generated by Django 5.0.6 on 2024-06-05 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0028_crcreate_creditaccount_event'),
    ]

    operations = [
        migrations.RunSQL('''
               DROP EVENT update_interest;
                ''')
    ]
