# Generated by Django 5.0.6 on 2024-06-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0035_loan_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default.jpg', upload_to='avatars/'),
        ),
    ]
