# Generated by Django 5.0.6 on 2024-06-09 02:59

from django.db import migrations


def change_user_avatar(apps, schema_editor):
    User = apps.get_model('bank_management', 'User')
    for user in User.objects.all():
        user.avatar = 'avatars/default.png'
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0037_alter_user_avatar'),
    ]

    operations = [
        migrations.RunPython(change_user_avatar),
    ]
