# Generated by Django 5.0.6 on 2024-06-11 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0042_create_loan_event'),
    ]

    operations = [
         migrations.RunSQL(
            """
            DROP EVENT IF EXISTS check_loan_overdue;
            """
        ),
        migrations.RunSQL(
            """
            CREATE EVENT IF NOT EXISTS check_loan_overdue
            ON SCHEDULE EVERY 1 DAY
            STARTS CURRENT_TIMESTAMP
            DO
            BEGIN
                UPDATE bank_management_loan
                SET loanStatus = 'OVERDUE'
                WHERE loanDate + INTERVAL loanDays DAY < CURRENT_DATE AND loanStatus = 'ISSUED';
                
                UPDATE bank_management_loan
                SET interest = interest + amount * interestRate * 5
                WHERE loanStatus = 'OVERDUE';
            END;
            """
        ),
    ]
