# Generated by Django 5.0.6 on 2024-06-12 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0043_create_loan_event11'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            CREATE TRIGGER adjust_total_assets
            AFTER INSERT ON bank_management_credittransaction
            FOR EACH ROW
            BEGIN
                IF NEW.transactionType = 'CONSUME' THEN
                    UPDATE bank_management_branch
                    SET totalAssets = totalAssets - NEW.amount
                    WHERE branchCode = (SELECT branchCode FROM bank_management_creditaccount WHERE accountId = NEW.creditAccount_id);
                ELSEIF NEW.transactionType = 'REPAYMENT' THEN
                    UPDATE bank_management_branch
                    SET totalAssets = totalAssets + NEW.amount
                    WHERE branchCode = (SELECT branchCode FROM bank_management_creditaccount WHERE accountId = NEW.creditAccount_id);
                END IF;
            END;
            '''
        )
    ]
