# Generated by Django 5.0.6 on 2024-06-12 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_management', '0044_create_credi_transaction_trigger'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            DROP EVENT IF EXISTS calculate_interest;
            '''
        ),
        migrations.RunSQL(
            '''
            CREATE EVENT IF NOT EXISTS calculate_interest
            ON SCHEDULE EVERY 1 DAY
            STARTS CURRENT_TIMESTAMP
            DO
            BEGIN
                DECLARE done INT DEFAULT FALSE;
                DECLARE accId INT;
                DECLARE interest DECIMAL(10,2);
                DECLARE cur CURSOR FOR SELECT accountId, balance * interestRate FROM bank_management_savingsaccount WHERE balance > 0;
                DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

                OPEN cur;

                read_loop: LOOP
                    FETCH cur INTO accId, interest;
                    IF done THEN
                        LEAVE read_loop;
                    END IF;
                    UPDATE bank_management_savingsaccount SET balance = balance + interest WHERE accountId = accId;
                    UPDATE bank_management_branch
                    JOIN bank_management_savingsaccount ON bank_management_branch.branchCode = bank_management_savingsaccount.branchCode
                    SET totalAssets = totalAssets - interest
                    WHERE bank_management_savingsaccount.accountId = accId;
                END LOOP;

                CLOSE cur;
            END;
            '''
        ),
    ]
